### ISSUE TITLE
[BUG]: Traceback on `pulse build`

### ISSUE THREAD

**Issue by Mergevos** [pulsepm/pulse#55]
**Describe the bug**
Title says it all. Only if there are no `requirements` table found in `pulse.toml`

**To Reproduce**
1. Run `pulse build` with no `requirements` table.

**Expected behavior**
Throw an error

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Mergevos** [comment]
seems i don't know how i produced this error, so I'll close this, since this works well...

**Comment by mysy00** [comment]
I fixed it here: https://github.com/pulsepm/pulse/pull/67
Sorry, I haven’t seen this issue earlier.
